---
## New role to give GET access to endpoints on Kubernetes API
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: get-endpoints
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-endpoints
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: get-endpoints
  apiGroup: rbac.authorization.k8s.io

---
## pinger service
apiVersion: v1
kind: Service
metadata:
  name: pinger
spec:
  type: ClusterIP
  selector:
    app: pinger
  ports:
  - port: 5005
    targetPort: 5005


---
## pinger (d3)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger-deployment
  labels:
    app: pinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
      - name: pinger
        image: moohh/pinger
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5005"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: NAMESPACE
          value: "default"
        - name: PROCESS_INTERVAL
          value: "3000"
        - name: RANDOM_PERCENT
          value: "0"
        ports:
        - containerPort: 5005